### ISSUE TITLE
No fingerprint option

### ISSUE THREAD

**Issue by root-Dante42** [cawilliamson/treble_voltage#54]
Hi
I updated my VoltageOS 3.7 to the latest VoltageOS 4.2 and the fingerprint setting is gone, and I can't even unlock my phone with my fingerprint, if I go into settings and use search, searching for fingerprint it finds the add fingerprint option but I can't add it.

Thanks for your work!

My devices is motorola moto g62 5g

**Comment by cawilliamson** [comment]
There were breakages for fingerprint support in my earlier unreleased test builds but I added a patch which resolved it so very odd that this is happening for you.

It *may* be necessary to perform a clean install (i.e. full data wipe) to get this to work properly though as it may have changed something under the hood.

**Comment by root-Dante42** [comment]
I can't do a full data wipe now because I have all my data on the phone, I guess I'll have to keep it like this for now

**Comment by diamantexv01** [comment]
I done a clean install and there no fingerprint unlock settings.

Xiaomi Mi A2 (jasmine_sprout)

**Comment by cawilliamson** [comment]
I have an idea actually - apparently if you set a certain prop it may resolve the issue and I believe in your cases - it will. I'm trying to add it to the TrebleApp now.

**Comment by cawilliamson** [comment]
https://github.com/cawilliamson/treble_voltage/releases/tag/4.2-20250312.103921

Could you try installing this build and then entering the TrebleApp (under Settings => System) and toggling on "Treat virtual sensors as real", then reboot?

Hopefully this should solve the fingerprint issue with your device.

**Comment by root-Dante42** [comment]
i try toggling on "Treat virtual sensors as real" and then reboot but don't work

**Comment by diamantexv01** [comment]
For my Xiaomi Mi A2 (jasmine_sprout) this option will make the phone stuck at the boot logo.

[logcat.log](https://github.com/user-attachments/files/19211148/logcat.log)

**Comment by DevHamid** [comment]
> https://github.com/cawilliamson/treble_voltage/releases/tag/4.2-20250312.103921
> 
> Could you try installing this build and then entering the TrebleApp (under Settings => System) and toggling on "Treat virtual sensors as real", then reboot?
> 
> Hopefully this should solve the fingerprint issue with your device.

Same issue, fingerprint option gone on MI 6X. After toggling on that virtual sensor, phone stuck endlessly on VoltageOS booting logo without cant enter menu.

Also wifi still cant connect.

**Comment by cawilliamson** [comment]
> Also wifi still cant connect.

You likely need to turn off WPA3/SAE in TrebleApp.

**Comment by cawilliamson** [comment]
Regarding the original issue - please try the new build and report back:

https://github.com/cawilliamson/treble_voltage/releases/tag/4.2-20250313.120122

**Comment by root-Dante42** [comment]
I install the last build and try reboot with and without  "Treat virtual sensors as real" on but don't work

**Comment by cawilliamson** [comment]
Please provide me with a full logcat from boot until your device finishes booting and I'll take a look through it.

**Comment by root-Dante42** [comment]
[logcat.txt](https://github.com/user-attachments/files/19247723/logcat.txt)

**Comment by cawilliamson** [comment]
@root-Dante42 @diamantexv01 What arch are your devices? arm64 or arm32_binder64?

**Comment by root-Dante42** [comment]
Arm64

**Comment by diamantexv01** [comment]
arm64

**Comment by 4adbfa76** [comment]
arm32_binder64

**Comment by Technical06** [comment]
> [@root-Dante42](https://github.com/root-Dante42) [@diamantexv01](https://github.com/diamantexv01) What arch are your devices? arm64 or arm32_binder64?

arm64 and im facing the same issue for broken fingerprint scanner also can u tell me how u fixed broken wifi for 4.14 kernel on this build , wifi is only working on this voltage OS gsi not any other a15 gsi

**Comment by cawilliamson** [comment]
> arm64 and im facing the same issue for broken fingerprint scanner also can u tell me how u fixed broken wifi for 4.14 kernel on this build , wifi is only working on this voltage OS gsi not any other a15 gsi

It seems that fingerprinting is broken on a lot of devices across basically all GSIs that I'm aware of right now.

As for the WiFi patches - I'm not doing anything special regarding WiFi that I'm aware of. Just running the absolute latest TrebleDroid patches. On other ROMs have you tried disabling WPA3/SAE in TrebleApp?

**Comment by Technical06** [comment]
> It seems that fingerprinting is broken on a lot of devices across basically all GSIs that I'm aware of right now.
> 
> As for the WiFi patches - I'm not doing anything special regarding WiFi that I'm aware of. Just running the absolute latest TrebleDroid patches. On other ROMs have you tried disabling WPA3/SAE in TrebleApp?

ill try but wifi is working fine for me , so i guess no need to mess with it

**Comment by matheuscZig** [comment]
> https://github.com/cawilliamson/treble_voltage/releases/tag/4.2-20250312.103921
> 
> Could you try installing this build and then entering the TrebleApp (under Settings => System) and toggling on "Treat virtual sensors as real", then reboot?
> 
> Hopefully this should solve the fingerprint issue with your device.

galaxy a11 in this build bootloop after turned on "treat virtual sensors as real" arm64

**Comment by hustlewithvikram** [comment]
@cawilliamson same here i dont have a fingerprint option on the latest release of voltage os, arm64 unisoc device. Also can you tell me ow can i make the quick tiles corners round ?

**Comment by diamantexv01** [comment]
I was testing with my redmi note 13 pro 5g(garnet), and no fingerprint option also.
EDIT: garnet is android 15

**Comment by cawilliamson** [comment]
There is no fingerprints on many devices on all GSIs right now. This isn't a Voltage specific issue.

**Comment by Zulfi121** [comment]
Hello, what is tbm13? Can I flash this 15th may build on my mtk device?
Thanks

**Comment by PalmDevs** [comment]
The latest experimental build as of now (`4.3-20250516.141346`) is working for me on SM-A135F even without the "Treat virtual sensors as real" turned on. Nice work!

**Comment by PalmDevs** [comment]
The latest experimental build as of now (`4.3-20250516.141346`) is working for me on SM-A135F even without the "Treat virtual sensors as real" option turned on. Nice work!

**Comment by diamantexv01** [comment]
With this latest 4.3-20250516.141346 firmware:
- didn't work at Redmi note 13 pro 5g (in-display fingerprint reader) although the option to add a fingerprint is there, but don't react when I press the fingerprint reader area in-display. (can't risk bootloop right now enabling "Treat virtual sensors as real")
- worked at Mi A2(rear fingerprint reader)

**Comment by diamantexv01** [comment]
Hi @cawilliamson, 
I could test your debug rom today:
- [DEBUG ONLY] VoltageOS 4.3-20250529.070616
- redmi note 13 pro 5g (garnet)

The problem persists:
> (in-display fingerprint reader) although the option to add a fingerprint is there, but don't react when I press the fingerprint reader area in-display. 

Logcat:
- Before enabling "treat virtual sensors as real":  [logcat_before.log](https://github.com/user-attachments/files/20510125/logcat_before.log)
- After enabling "treat virtual sensors as real": [logcat_after.log](https://github.com/user-attachments/files/20510130/logcat_after.log) (stuck at voltageos boot logo animation)

**Comment by cawilliamson** [comment]
All remaining sensor problems at this point will need to be raised as tickets on: https://github.com/TrebleDroid/treble_experimentations/issues

I've done as much as I can from my side on this issue.
